"""initial schema

Revision ID: c6686318aa10
Revises: 
Create Date: 2026-09-25 07:45:32.133773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6686318aa10'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_sessions',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('play_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('zalo_group_id', sa.String(length=64), nullable=True),
    sa.Column('poll_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'OPEN', 'LOCKED', 'TEAM_GENERATED', 'FINALIZED', 'PUBLISHED', name='sessionstatus', native_enum=False, length=20), nullable=False),
    sa.Column('team_count', sa.Integer(), nullable=True),
    sa.Column('player_per_team', sa.Integer(), nullable=True),
    sa.Column('substitute_count', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members',
    sa.Column('zalo_user_id', sa.String(length=64), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('nickname', sa.String(length=60), nullable=True),
    sa.Column('skill_level', sa.Enum('GIOI', 'TRUNG_BINH', 'YEU', 'UNKNOWN', name='skilllevel', native_enum=False, length=20), nullable=False),
    sa.Column('skill_score', sa.Float(), nullable=False),
    sa.Column('preferred_position', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='memberstatus', native_enum=False, length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zalo_user_id')
    )
    op.create_table('message_templates',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('performed_by', sa.String(length=120), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['match_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_session_id'), 'audit_logs', ['session_id'], unique=False)
    op.create_table('publish_logs',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('message_content', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', name='publishstatus', native_enum=False, length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['match_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publish_logs_session_id'), 'publish_logs', ['session_id'], unique=False)
    op.create_table('session_participants',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=True),
    sa.Column('participant_name', sa.String(length=120), nullable=False),
    sa.Column('participant_type', sa.Enum('MEMBER', 'GUEST', name='participanttype', native_enum=False, length=20), nullable=False),
    sa.Column('skill_level', sa.Enum('GIOI', 'TRUNG_BINH', 'YEU', 'UNKNOWN', name='skilllevel', native_enum=False, length=20), nullable=False),
    sa.Column('skill_score', sa.Float(), nullable=False),
    sa.Column('attendance_source', sa.Enum('ZALO', 'MANUAL', 'GUEST', name='attendancesource', native_enum=False, length=20), nullable=False),
    sa.Column('attendance_status', sa.Enum('CONFIRMED', 'WAITING', 'CANCELLED', name='attendancestatus', native_enum=False, length=20), nullable=False),
    sa.Column('is_substitute', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('guest_sequence', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['match_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_participants_session_id'), 'session_participants', ['session_id'], unique=False)
    op.create_table('teams',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('strength_score', sa.Float(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['match_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_session_id'), 'teams', ['session_id'], unique=False)
    op.create_table('team_members',
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('participant_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_by', sa.Enum('SYSTEM', 'ADMIN', name='assignedby', native_enum=False, length=20), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['session_participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participant_id')
    )
    op.create_index(op.f('ix_team_members_team_id'), 'team_members', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_members_team_id'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_teams_session_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_session_participants_session_id'), table_name='session_participants')
    op.drop_table('session_participants')
    op.drop_index(op.f('ix_publish_logs_session_id'), table_name='publish_logs')
    op.drop_table('publish_logs')
    op.drop_index(op.f('ix_audit_logs_session_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('message_templates')
    op.drop_table('members')
    op.drop_table('match_sessions')
    # ### end Alembic commands ###
