"""add zalo poll state table

Revision ID: c800936c6bd0
Revises: c6686318aa10
Create Date: 2026-09-25 08:50:26.686149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c800936c6bd0'
down_revision: Union[str, None] = 'c6686318aa10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zalo_poll_state',
    sa.Column('last_update_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zalo_poll_state')
    # ### end Alembic commands ###
